### ISSUE TITLE
RuntimeError: cannot discover struct layout 

### ISSUE THREAD

**Issue by embg** [pyopencl/pyopencl#130] opened 2016-07-05 18:07 UTC
I'm trying to use a struct type with pyopencl as described [here](https://documen.tician.de/pyopencl/howto.html). However, I get an error:
```
Traceback (most recent call last):
  File "/home/emg3/miniconda2/envs/pysr/lib/python3.5/site-packages/pytools/__init__.py", line 427, in _deco
    return func._memoize_dic[args]
AttributeError: 'function' object has no attribute '_memoize_dic'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mwe.py", line 10, in <module>
    my_struct, my_struct_c_decl = cl.tools.match_dtype_to_c_struct(ctx.devices[0], "my_struct", my_struct)
  File "<decorator-gen-3>", line 2, in match_dtype_to_c_struct
  File "/home/emg3/miniconda2/envs/pysr/lib/python3.5/site-packages/pytools/__init__.py", line 430, in _deco
    result = func(*args)
  File "/home/emg3/miniconda2/envs/pysr/lib/python3.5/site-packages/pyopencl/tools.py", line 605, in match_dtype_to_c_struct
    "cannot discover struct layout on '%s'" % device)
RuntimeError: cannot discover struct layout on '<pyopencl.Device 'Quadro NVS 295' on 'NVIDIA CUDA' at 0x24cc120>'
```
Here's a MWE:
```
import pyopencl as cl
import pyopencl.tools
import numpy as np

ctx = cl.create_some_context(interactive=False)
my_struct = np.dtype([('val', np.float32),
                      ('op',  np.uint8),
                      ('a',   np.uint8),
                      ('b',   np.uint8)])
my_struct, my_struct_c_decl = cl.tools.match_dtype_to_c_struct(ctx.devices[0], "my_struct", my_struct)
#RuntimeError: cannot discover struct layout on '<pyopencl.Device 'Quadro NVS 295' on 'NVIDIA CUDA' at 0x1917670>'
```
I found that it works fine if I replace uint8 with uint32, but the error persists with uint16.

**Comment by inducer** [comment] 2016-07-06 08:54
Doesn't reproduce for me on any of these. What version of PyOpenCL? What version of the Nvidia driver?

```
[0] <pyopencl.Platform 'NVIDIA CUDA' at 0x27b6310>
[1] <pyopencl.Platform 'AMD Accelerated Parallel Processing' at 0x7f7dcf6b5430>
[2] <pyopencl.Platform 'Portable Computing Language' at 0x7f7dcba763c0>
[3] <pyopencl.Platform 'Intel(R) OpenCL' at 0x283e4d0>
```

**Comment by embg** [comment] 2016-07-06 15:53
pyopencl version:
`pyopencl                  2016.1                    <pip>`

pyopencl platform selection:
`[0] <pyopencl.Platform 'NVIDIA CUDA' at 0x1cef570>`

Output of `clinfo`:
```
Number of platforms                               1
  Platform Name                                   NVIDIA CUDA
  Platform Vendor                                 NVIDIA Corporation
  Platform Version                                OpenCL 1.1 CUDA 6.5.51
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts 
  Platform Extensions function suffix             NV

  Platform Name                                   NVIDIA CUDA
Number of devices                                 1
  Device Name                                     Quadro NVS 295
  Device Vendor                                   NVIDIA Corporation
  Device Vendor ID                                0x10de
  Device Version                                  OpenCL 1.0 CUDA
  Driver Version                                  340.96
  Device OpenCL C Version                         OpenCL C 1.0 
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Device Topology (NV)                            PCI-E, 02:00.0
  Max compute units                               1
  Max clock frequency                             1300MHz
  Compute Capability (NV)                         1.1
  Max work item dimensions                        3
  Max work item sizes                             512x512x64
  Max work group size                             512
  Preferred work group size multiple              32
  Warp size (NV)                                  32
  Preferred / native vector sizes                 
    char                                                 1 / 1       
    short                                                1 / 1       
    int                                                  1 / 1       
    long                                                 1 / 1       
    half                                                 0 / 0        (n/a)
    float                                                1 / 1       
    double                                               0 / 0        (n/a)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Double-precision Floating-point support         (n/a)
  Address bits                                    32, Little-Endian
  Global memory size                              267714560 (255.3MiB)
  Error Correction support                        No
  Max memory allocation                           134217728 (128MiB)
  Unified memory for Host and Device              No
  Integrated memory (NV)                          No
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       2048 bits (256 bytes)
  Global Memory cache type                        None
  Image support                                   Yes
    Max number of samplers per kernel             16
    Max 2D image size                             4096x16383 pixels
    Max 3D image size                             2048x2048x2048 pixels
    Max number of read image args                 128
    Max number of write image args                8
  Local memory type                               Local
  Local memory size                               16384 (16KiB)
  Registers per block (NV)                        8192
  Max constant buffer size                        65536 (64KiB)
  Max number of constant args                     9
  Max size of kernel argument                     4352 (4.25KiB)
  Queue properties                                
    Out-of-order execution                        Yes
    Profiling                                     Yes
  Profiling timer resolution                      1000ns
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            No
    Kernel execution timeout (NV)                 Yes
  Concurrent copy and kernel execution (NV)       No
    Number of async copy engines                  0
  Device Available                                Yes
  Compiler Available                              Yes
  Device Extensions                               cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts  cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics 

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  NVIDIA CUDA
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [NV]
  clCreateContext(NULL, ...) [default]            Success [NV]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  No platform

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.8
  ICD loader Profile                              OpenCL 1.2
	NOTE:	your OpenCL library declares to support OpenCL 1.2,
		but it seems to support up to OpenCL 2.1 too.
```

**Comment by inducer** [comment] 2016-07-07 14:41
This looks like a bug in the Nvidia OpenCL compiler that got fixed in (at least) CUDA 7.5. Could you try upgrading?

**Comment by Poulpy21** [comment] 2016-09-02 10:59
Same problem with an AMD card here on ubuntu 16.04.
With the same code sample, any np.int8 or np.uint8 dtype fails to match the c_struct.

> Traceback(most recent call last):
  File "test.py", line 10, in <module>
    my_struct, my_struct_c_decl = cl.tools.match_dtype_to_c_struct(ctx.devices[0], "my_struct", my_struct)
  File "<decorator-gen-3>", line 2, in match_dtype_to_c_struct
  File "/usr/local/lib/python2.7/dist-packages/pytools/__init__.py", line 430, in _deco
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/pyopencl/tools.py", line 605, in match_dtype_to_c_struct
    "cannot discover struct layout on '%s'" % device)

`RuntimeError: Cannot discover struct layout on '<pyopencl.Device 'AMD CAPE VERDE (DRM 2.43.0, LLVM 3.8.0)' on 'Clover' at 0x2b15288>'`

**Comment by inducer** [comment] 2016-09-03 02:52
This happens when a compiler reports `offsetof(struct_value, m) > sizeof(struct_value)`, which doesn't make a whole lot of sense. Generally, that indicates a compiler bug. Not sure I know what to do other than yell at the compiler author to fix their product...

FWIW, I've improved the error message:

```
            raise RuntimeError(
                    "OpenCL compiler reported offsetof() past sizeof() "
                    "for struct layout on '%s'. "
                    "This makes no sense, and it's usually indicates a "
                    "compiler bug. "
                    "Refusing to discover struct layout." % device)
```

**Closed** 2016-09-03 02:53 UTC

**Comment by Poulpy21** [comment] 2016-09-09 08:39
I just found the source of this bug: when the size of np.intp and opencl size_t do not match, transferring back the buffer containing the computed struct size and offsets fails on devices that declares a CL_DEVICE_ADDRESS_BITS different from host.
Changing np.intp to np.uint32 and size_t to uint in `pyopencl/tools.py` fixes this issue.
