### ISSUE TITLE
Adding support for FPGA boards

### ISSUE THREAD

**Issue by nachiket** [pyopencl/pyopencl#132] opened 2016-08-04 07:00 UTC
I've been trying to figure out how to add PyOpenCL support for Altera FPGA boards, and have probably reached a CFFI link flag issue that I cannot figure out.

Here's the story so far...
https://paper.dropbox.com/doc/PyOpenCL-with-Altera-FPGAs-8ojfCVUBhiz7UOjRTIaFe

TLDR: I'm able to get `import pyopencl as cl ` to work without issue, but any operation on the cl object such as `cl.create_some_context()` throws this error

> Error: Did not find any board vendor files in /opt/Altera/OpenCL/Boards/ to load board library at runtime. Either link to the board library while compiling your host code or refer to your board vendor's documentation on how to install the board library so that it can be loaded at runtime.
> Warning: Cannot find any Altera board libraries. No Altera devices will be loaded.
> Error: Could not load board libraries successfully.

I have seen similar errors when running [clinfo](https://github.com/Oblomov/clinfo) which I've been able to patch trivially by passing the following link flags. Note: This is specifically for the DE5-NET FPGA board.
` LDLIBS=-L/opt/altera/16.0/hld/board/terasic/de5net/linux64/lib -L/opt/altera/16.0/hld/host/linux64/lib -Wl,--no-as-needed -lalteracl -lalterahalmmd -laltera_apb_14_0_mmd`

However, despite editing siteconf.py and setup.py with these paths, there is something funky going on at runtime. 

siteconf.py:
>   CL_TRACE = False
>   CL_ENABLE_GL = False
>   CL_USE_SHIPPED_EXT = True
>   CL_PRETEND_VERSION = '1.1'
>   CL_INC_DIR = []
>   CL_LIB_DIR = ['/opt/altera/16.0/hld/board/terasic/de5net/linux64/lib', '/opt/altera/16.0/hld/host/linux64/lib']
>   CL_LIBNAME = ['alteracl', 'alterahalmmd', 'altera_apb_14_0_mmd']
>   CXXFLAGS = ['-std=c++0x']
>   LDFLAGS = ['-Wl,--no-as-needed','-Wl,--rpath,/opt/altera/16.0/hld/board/terasic/de5net/linux64/lib','-Wl,--rpath,/opt/altera/16.0/hld/host/linux64/lib']

For setup.py, only edited a few lines ~65-75 line numbers

> default_libs = ["alterahalmmd","altera_apb_14_0_mmd","alteracl"]
> default_libdir = ["/opt/altera/16.0/hld/board/terasic/de5net/linux64/lib","/opt/altera/16.0/hld/host/linux64/lib"]
> default_ldflags = ["-Wl,--no-as-needed","-Wl,--rpath,/opt/altera/16.0/hld/board/terasic/de5net/linux64/lib","-Wl,--rpath,/opt/altera/16.0/hld/host/linux64/lib"]

**Comment by inducer** [comment] 2016-08-04 15:36
Maybe you could try adding those paths to the `$LD_LIBRARY_PATH` environment variable? Also, please use the mailing list (rather than the bug tracker) for tech support. Closing here.

**Closed by inducer** 2016-08-04 15:36 UTC

**Comment by nachiket** [comment] 2016-08-04 16:02
I did try that.. didn't work.. there's something about the
-Wl,--no-as-needed flag that plays improperly with cffi..

**Comment by mohmsslk** [comment] 2016-09-15 19:17
Hello Nachiket,

I want to use PyOpenCL but I need some information, I hope I find it with you.
wich host you are using ?
wich board you are using?
do you conact the host and th kernel through PCI?
and what OS  u use in host ?
another thing, can I use PyOpenCL with the following things:
Host ARM CPU 2core.
FPGA Altera Cyclon 5 with ARM CPU 2 core Board insid the ship.
and with linux image to run in host.

Im waiting for your respons and I hope to find this information with you.

Thanks in advance

**Comment by vellamike** [comment] 2017-07-12 09:52
@mohmsslk I was able to get pyopencl to work with my Altera board (a10gx  - but this should work for any board) thanks to @nachiket's work on this. I installed using pip as follows:

    LDFLAGS="-Wl,--no-as-needed" python3 -m pip install --upgrade --no-binary pyopencl --no-cache-dir pyopencl

@inducer would it be possible to add the `--no-as-needed` linker flag to pyopencl setup? I am not sure if there are any downsides to this and it would enable Altera FPGA support out of the box.

In his [mailing list post](https://lists.tiker.net/pipermail/pyopencl/2016-August/002211.html) and [notes](https://paper.dropbox.com/doc/PyOpenCL-with-Altera-FPGAs-8ojfCVUBhiz7UOjRTIaFe) @nachiket talks about needing to do things like use `enqueue_nd_range_kernel` instead of the `__call__` method on the kernel and add BSP library paths to the `setup.py` but the only change I needed to make was setting the `LDFLAGS` environment variable. This is probably because I am using AOCL version 17.0.


P.S I will write to the mailing list about this too but wanted to leave this comment here because it's the first thing which comes up when searching for this issue. Also, there doesn't seem to be a way on the mailing list to reply to a previous comment so I think Github issues is much better for this sort of thing.

**Comment by inducer** [comment] 2017-07-12 14:11
@vellamike e745087 adds this by default for Linux builds. It doesn't seem to hurt anything in my environment. We'll see how badly it blows up elsewhere. Let me know if that addresses your request.

**Comment by vellamike** [comment] 2017-07-12 16:08
thank you @inducer - I can confirm that this appears to fix my problem.

**Comment by vellamike** [comment] 2017-07-14 09:03
@nachiket I tried with AOCL 16.1 and it worked, so I'm not sure why your installation appears to have been more complex than mine.

**Comment by nfkok** [comment] 2019-11-04 12:32
Hi, does anyone know how can I do the pyopencl installation in windows to use Intel FPGA? What is the 'LDFLAGS' equivalent in Windows?
